# Generated by Django 4.2.13 on 2026-07-20 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_unique_id", models.IntegerField(blank=True, null=True)),
                ("player_name_raw", models.CharField(max_length=255)),
                ("age_at_transfer", models.IntegerField(blank=True, null=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("position", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "short_position",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "market_value_at_transfer",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("dealing_club", models.CharField(max_length=255)),
                (
                    "dealing_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fee", models.CharField(blank=True, max_length=100, null=True)),
                ("movement", models.CharField(max_length=20)),
                ("window", models.CharField(max_length=20)),
                (
                    "league_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("year", models.IntegerField()),
                ("is_loan", models.BooleanField(blank=True, null=True)),
                ("loan_status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers",
                        to="clubs.club",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["club"], name="transfers_t_club_id_567372_idx")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="transfer",
            constraint=models.UniqueConstraint(
                fields=(
                    "player_name_raw",
                    "year",
                    "window",
                    "movement",
                    "club",
                    "dealing_club",
                ),
                name="uniq_transfer_event",
            ),
        ),
    ]
