"""Tests for the correctness-oracle snapshot (03-07-PLAN.md Task 1) --
Phase 3 Success Criterion 2.

`test_snapshot_coverage` proves the versioned oracle CSV, once generated by
`manage.py generate_scoring_oracle`, has exactly the 7 required columns,
covers essentially the whole real player population, and never silently
zero-fills a score (RMM in particular must be non-null for the large
majority of players, and no score column can be 100% null). It degrades
gracefully (skip, not fail) when the CSV hasn't been generated yet -- this
command does a full-population run that isn't meant to happen inside every
test invocation.

`test_manifest_records_context` proves MANIFEST.md records the snapshot
version and the per-score population/context notes the plan requires.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd
import pytest

from scoring.tests._parity_helpers import find_latest_oracle_csv

ORACLE_DIR = Path(__file__).resolve().parents[1] / "oracle"
MANIFEST_PATH = ORACLE_DIR / "MANIFEST.md"

EXPECTED_COLUMNS = [
    "player_id",
    "player_name",
    "main_position",
    "rmm",
    "cs",
    "tfm",
    "transfer_probability",
]


@pytest.mark.django_db
def test_snapshot_coverage(real_data_available):
    from players.models import Player

    csv_path = find_latest_oracle_csv()
    if csv_path is None:
        pytest.skip(
            "No oracle CSV found in scoring/oracle/ -- run "
            "`python manage.py generate_scoring_oracle` first to produce one."
        )

    df = pd.read_csv(csv_path)

    assert list(df.columns) == EXPECTED_COLUMNS

    live_player_count = Player.objects.count()
    assert len(df) > 40000
    # Within 5% of the live Player count (documented deviation allowance --
    # 03-07-PLAN.md acceptance criteria).
    assert abs(len(df) - live_player_count) <= 0.05 * live_player_count

    # RMM must be non-null for the large majority of players -- never a
    # spurious/silent 0 manufactured from a missing column.
    assert df["rmm"].notna().mean() > 0.5
    non_null_rmm = df["rmm"].dropna()
    assert ((non_null_rmm >= 0) & (non_null_rmm <= 100)).all()

    # No score column may be 100% null -- that would mean the whole-
    # population run never actually computed anything for that score.
    for col in ["rmm", "cs", "tfm", "transfer_probability"]:
        assert df[col].notna().any(), f"{col} is 100% null in the oracle snapshot"


def test_manifest_records_context():
    if not MANIFEST_PATH.exists():
        pytest.skip(
            "No MANIFEST.md found in scoring/oracle/ -- run "
            "`python manage.py generate_scoring_oracle` first to produce one."
        )

    text = MANIFEST_PATH.read_text()

    assert "snapshot_version" in text
    assert "RMM" in text
    assert "Compatibility Score" in text
    assert "TFM" in text
    assert "Transfer Probability" in text
    assert "context-free" in text.lower() or "current club" in text.lower()
