# Generated by Django 4.2.13 on 2026-07-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("league", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("manager", models.CharField(blank=True, max_length=255, null=True)),
                ("formation", models.CharField(blank=True, max_length=50, null=True)),
                ("source_unique_id", models.IntegerField(blank=True, null=True)),
                ("control_possession", models.FloatField(blank=True, null=True)),
                ("gegenpressing", models.FloatField(blank=True, null=True)),
                ("direct_play", models.FloatField(blank=True, null=True)),
                ("defensive_counter_attack", models.FloatField(blank=True, null=True)),
                ("tiki_taka", models.FloatField(blank=True, null=True)),
                ("counter_attack", models.FloatField(blank=True, null=True)),
                ("wing_play", models.FloatField(blank=True, null=True)),
                ("low_block", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
