# Generated by Django 5.2.16 on 2026-07-21 06:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("unique_id", models.IntegerField(unique=True)),
                ("player", models.CharField(max_length=255)),
                ("season", models.CharField(blank=True, max_length=32, null=True)),
                ("legacy_total_score", models.FloatField(blank=True, null=True)),
                ("league", models.CharField(blank=True, max_length=255, null=True)),
                ("positions", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "main_position",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("position", models.CharField(blank=True, max_length=50, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("market_value", models.BigIntegerField(blank=True, null=True)),
                ("contract_expires", models.DateField(blank=True, null=True)),
                (
                    "birth_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "passport_country",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("foot", models.CharField(blank=True, max_length=20, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("weight", models.IntegerField(blank=True, null=True)),
                ("on_loan", models.BooleanField(blank=True, null=True)),
                ("Matches_played", models.FloatField(blank=True, null=True)),
                ("Minutes_played", models.FloatField(blank=True, null=True)),
                ("Goals", models.FloatField(blank=True, null=True)),
                ("xG", models.FloatField(blank=True, null=True)),
                ("Assists", models.FloatField(blank=True, null=True)),
                ("xA", models.FloatField(blank=True, null=True)),
                ("Duels_per_90", models.FloatField(blank=True, null=True)),
                ("Duels_won_percentage", models.FloatField(blank=True, null=True)),
                (
                    "Successful_defensive_actions_per_90",
                    models.FloatField(blank=True, null=True),
                ),
                ("Defensive_duels_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Defensive_duels_won_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("Aerial_duels_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Aerial_duels_won_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("Sliding_tackles_per_90", models.FloatField(blank=True, null=True)),
                ("PAdj_Sliding_tackles", models.FloatField(blank=True, null=True)),
                ("Shots_blocked_per_90", models.FloatField(blank=True, null=True)),
                ("Interceptions_per_90", models.FloatField(blank=True, null=True)),
                ("PAdj_Interceptions", models.FloatField(blank=True, null=True)),
                ("Fouls_per_90", models.FloatField(blank=True, null=True)),
                ("Yellow_cards", models.FloatField(blank=True, null=True)),
                ("Yellow_cards_per_90", models.FloatField(blank=True, null=True)),
                ("Red_cards", models.FloatField(blank=True, null=True)),
                ("Red_cards_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Successful_attacking_actions_per_90",
                    models.FloatField(blank=True, null=True),
                ),
                ("Goals_per_90", models.FloatField(blank=True, null=True)),
                ("Non_penalty_goals", models.FloatField(blank=True, null=True)),
                ("Non_penalty_goals_per_90", models.FloatField(blank=True, null=True)),
                ("xG_per_90", models.FloatField(blank=True, null=True)),
                ("Head_goals", models.FloatField(blank=True, null=True)),
                ("Head_goals_per_90", models.FloatField(blank=True, null=True)),
                ("Shots", models.FloatField(blank=True, null=True)),
                ("Shots_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Shots_on_target_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "Goal_conversion_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("Assists_per_90", models.FloatField(blank=True, null=True)),
                ("Crosses_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Accurate_crosses_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "Crosses_from_left_flank_per_90",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "Accurate_crosses_from_left_flank_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "Crosses_from_right_flank_per_90",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "Accurate_crosses_from_right_flank_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "Crosses_to_goalie_box_per_90",
                    models.FloatField(blank=True, null=True),
                ),
                ("Dribbles_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Successful_dribbles_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("Offensive_duels_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Offensive_duels_won_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("Touches_in_box_per_90", models.FloatField(blank=True, null=True)),
                ("Progressive_runs_per_90", models.FloatField(blank=True, null=True)),
                ("Accelerations_per_90", models.FloatField(blank=True, null=True)),
                ("Received_passes_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Received_long_passes_per_90",
                    models.FloatField(blank=True, null=True),
                ),
                ("Fouls_suffered_per_90", models.FloatField(blank=True, null=True)),
                ("Passes_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Accurate_passes_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("Forward_passes_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Accurate_forward_passes_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("Back_passes_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Accurate_back_passes_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("Lateral_passes_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Accurate_lateral_passes_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "Short_medium_passes_per_90",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "Accurate_short_medium_passes_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("Long_passes_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Accurate_long_passes_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("Average_pass_length_m", models.FloatField(blank=True, null=True)),
                (
                    "Average_long_pass_length_m",
                    models.FloatField(blank=True, null=True),
                ),
                ("xA_per_90", models.FloatField(blank=True, null=True)),
                ("Shot_assists_per_90", models.FloatField(blank=True, null=True)),
                ("Second_assists_per_90", models.FloatField(blank=True, null=True)),
                ("Third_assists_per_90", models.FloatField(blank=True, null=True)),
                ("Smart_passes_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Accurate_smart_passes_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("Key_passes_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Passes_to_final_third_per_90",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "Accurate_passes_to_final_third_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "Passes_to_penalty_area_per_90",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "Accurate_passes_to_penalty_area_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("Through_passes_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Accurate_through_passes_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("Deep_completions_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Deep_completed_crosses_per_90",
                    models.FloatField(blank=True, null=True),
                ),
                ("Progressive_passes_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Accurate_progressive_passes_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("Conceded_goals", models.FloatField(blank=True, null=True)),
                ("Conceded_goals_per_90", models.FloatField(blank=True, null=True)),
                ("Shots_against", models.FloatField(blank=True, null=True)),
                ("Shots_against_per_90", models.FloatField(blank=True, null=True)),
                ("Clean_sheets", models.FloatField(blank=True, null=True)),
                ("Save_rate_percentage", models.FloatField(blank=True, null=True)),
                ("xG_against", models.FloatField(blank=True, null=True)),
                ("xG_against_per_90", models.FloatField(blank=True, null=True)),
                ("Prevented_goals", models.FloatField(blank=True, null=True)),
                ("Prevented_goals_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Back_passes_received_as_GK_per_90",
                    models.FloatField(blank=True, null=True),
                ),
                ("Exits_per_90", models.FloatField(blank=True, null=True)),
                ("Free_kicks_per_90", models.FloatField(blank=True, null=True)),
                ("Direct_free_kicks_per_90", models.FloatField(blank=True, null=True)),
                (
                    "Direct_free_kicks_on_target_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("Corners_per_90", models.FloatField(blank=True, null=True)),
                ("Penalties_taken", models.FloatField(blank=True, null=True)),
                (
                    "Penalty_conversion_percentage",
                    models.FloatField(blank=True, null=True),
                ),
                ("extended_stats", models.JSONField(blank=True, default=dict)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="players",
                        to="clubs.club",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerClubCompatibility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("club_name_raw", models.CharField(max_length=255)),
                ("position_group", models.CharField(max_length=8)),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compatibilities",
                        to="clubs.club",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibilities",
                        to="players.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayerRoleScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position_group", models.CharField(max_length=8)),
                ("role_name", models.CharField(max_length=100)),
                ("role_name_raw", models.CharField(max_length=150)),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_scores",
                        to="players.player",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["position"], name="players_pla_positio_2502c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["age"], name="players_pla_age_1c8a55_idx"),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["market_value"], name="players_pla_market__b3960b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["club"], name="players_pla_club_id_7dba43_idx"),
        ),
        migrations.AddIndex(
            model_name="playerclubcompatibility",
            index=models.Index(
                fields=["club", "-score"], name="players_pla_club_id_82023b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerclubcompatibility",
            index=models.Index(
                fields=["player", "-score"], name="players_pla_player__5ac939_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="playerclubcompatibility",
            constraint=models.UniqueConstraint(
                fields=("player", "club_name_raw"), name="uniq_player_clubname"
            ),
        ),
        migrations.AddConstraint(
            model_name="playerrolescore",
            constraint=models.UniqueConstraint(
                fields=("player", "role_name"), name="uniq_player_role"
            ),
        ),
    ]
