# Generated by Django 5.2.16 on 2026-07-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clubs", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="compatibility_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="financial_fit_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="impact_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="transfer_probability_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["-impact_score"], name="players_pla_impact__cedfec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["-compatibility_score"], name="players_pla_compati_f91953_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["-financial_fit_score"], name="players_pla_financi_8ec179_idx"
            ),
        ),
    ]
